"""Provider-neutral AI tool-calling contracts.

Defines canonical representations for tool definitions, tool calls, tool results,
chat messages, and provider adapter responses. Decouples domain logic from any
specific LLM vendor (OpenAI, Anthropic, Gemini, Local).
"""
from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import Field

from app.schemas.common import ContractModel


class ClaimType(str, Enum):
    VERIFIED = "verified"
    SCHEDULED = "scheduled"
    LIVE = "live"
    ESTIMATED = "estimated"
    RESEARCHED = "researched"
    UNKNOWN = "unknown"


class EvidenceItem(ContractModel):
    """Compact structured evidence item grounding a recommendation."""

    title: str = Field(min_length=1, description="Brief evidence headline or claim summary.")
    rationale: str = Field(min_length=1, description="Factual rationale grounding the recommendation.")
    claim_type: ClaimType = Field(default=ClaimType.VERIFIED, description="Truthfulness provenance classification.")
    source: str | None = Field(default=None, description="Authoritative service or dataset source.")
    confidence: str | None = Field(default=None, description="Confidence rating tier (e.g. 'high', 'moderate').")


class ToolStatus(str, Enum):
    OK = "ok"
    UNAVAILABLE = "unavailable"
    UNKNOWN = "unknown"
    INVALID = "invalid"
    ERROR = "error"


class ToolDefinition(ContractModel):
    """Provider-neutral tool declaration conforming to JSON Schema standards."""

    name: str = Field(min_length=1, description="Unique, stable tool identifier.")
    description: str = Field(min_length=1, description="Human-readable description of tool capability.")
    input_schema: dict[str, Any] = Field(
        default_factory=lambda: {"type": "object", "properties": {}},
        description="JSON Schema describing accepted input parameters.",
    )


class ToolCall(ContractModel):
    """Canonical model tool invocation request."""

    id: str = Field(
        default_factory=lambda: f"call_{uuid4().hex[:12]}",
        description="Unique identifier for this tool call invocation.",
    )
    name: str = Field(min_length=1, description="Name of the registered tool to invoke.")
    arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="Key-value arguments payload passed to the tool.",
    )


class ToolResult(ContractModel):
    """Canonical execution result returned by a registered tool."""

    tool_call_id: str | None = Field(default=None, description="Matching ToolCall ID if applicable.")
    tool_name: str = Field(min_length=1, description="Name of the tool that was executed.")
    status: ToolStatus = Field(default=ToolStatus.OK, description="Execution status.")
    data: Any = Field(default=None, description="Structured factual output returned by the domain service.")
    reason: str | None = Field(default=None, description="Human-readable reason for non-OK status.")
    error: str | None = Field(default=None, description="Error code or description if execution failed.")
    warnings: list[str] = Field(default_factory=list, description="Non-fatal warnings.")


class ChatRole(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ChatMessage(ContractModel):
    """Provider-neutral conversation message."""

    role: ChatRole = Field(description="Role of the message sender.")
    content: str | None = Field(default=None, description="Textual message content.")
    tool_calls: list[ToolCall] = Field(default_factory=list, description="Tool calls requested by assistant.")
    tool_call_id: str | None = Field(default=None, description="Matching tool call ID if role is tool.")
    name: str | None = Field(default=None, description="Tool name if role is tool.")
    image_urls: list[str] = Field(default_factory=list, description="Optional image URLs/base64 URIs for multimodal input.")


class FinishReason(str, Enum):
    STOP = "stop"
    TOOL_CALLS = "tool_calls"
    LENGTH = "length"
    ERROR = "error"


class AdapterResponse(ContractModel):
    """Provider-neutral response envelope emitted by AIProviderAdapter implementations."""

    content: str | None = Field(default=None, description="Textual response generated by the model.")
    tool_calls: list[ToolCall] = Field(default_factory=list, description="Tool invocations requested by the model.")
    finish_reason: FinishReason = Field(default=FinishReason.STOP, description="Reason model generation finished.")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Provider-neutral diagnostic metadata.")


class ProviderErrorCode(str, Enum):
    """Canonical classification for AI provider failure modes."""

    PROVIDER_UNAVAILABLE = "provider_unavailable"
    MISSING_CONFIGURATION = "missing_configuration"
    AUTHENTICATION_FAILURE = "authentication_failure"
    TIMEOUT = "timeout"
    MALFORMED_RESPONSE = "malformed_response"
    UNSUPPORTED_CAPABILITY = "unsupported_capability"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    PROVIDER_ERROR = "provider_error"


class AIProviderError(Exception):
    """Base exception for provider failures, guaranteeing secret masking."""

    def __init__(
        self,
        message: str,
        code: ProviderErrorCode = ProviderErrorCode.PROVIDER_ERROR,
        status_code: int | None = None,
        retryable: bool = False,
        provider: str | None = None,
    ) -> None:
        # Sanitize sensitive patterns if they ever appear
        sanitized_msg = self._sanitize(message)
        super().__init__(sanitized_msg)
        self.message = sanitized_msg
        self.code = code
        self.status_code = status_code
        self.retryable = retryable
        self.provider = provider

    @staticmethod
    def _sanitize(text: str) -> str:
        if not text:
            return ""
        import re
        # Redact bearer tokens, api keys, authorization headers
        redacted = re.sub(r"(?i)(bearer\s+)[a-zA-Z0-9_\-\.]{8,}", r"\1[REDACTED]", text)
        redacted = re.sub(r"(?i)(key[=:\s]+)[a-zA-Z0-9_\-\.]{8,}", r"\1[REDACTED]", redacted)
        redacted = re.sub(r"(?i)(authorization[=:\s]+)[^\s,;]+", r"\1[REDACTED]", redacted)
        return redacted


class ProviderUnavailableError(AIProviderError):
    """Provider endpoint is unreachable or offline."""

    def __init__(self, message: str = "AI provider is unavailable.", **kwargs: Any) -> None:
        super().__init__(message, code=ProviderErrorCode.PROVIDER_UNAVAILABLE, retryable=True, **kwargs)


class MissingConfigurationError(AIProviderError):
    """Provider configuration or credentials are absent."""

    def __init__(self, message: str = "AI provider configuration is missing.", **kwargs: Any) -> None:
        super().__init__(message, code=ProviderErrorCode.MISSING_CONFIGURATION, retryable=False, **kwargs)


class AuthenticationError(AIProviderError):
    """Authentication or authorization with the provider failed."""

    def __init__(self, message: str = "AI provider authentication failed.", **kwargs: Any) -> None:
        super().__init__(message, code=ProviderErrorCode.AUTHENTICATION_FAILURE, retryable=False, **kwargs)


class ProviderTimeoutError(AIProviderError):
    """Provider request timed out."""

    def __init__(self, message: str = "AI provider request timed out.", **kwargs: Any) -> None:
        super().__init__(message, code=ProviderErrorCode.TIMEOUT, retryable=True, **kwargs)


class MalformedProviderResponseError(AIProviderError):
    """Provider response body was invalid or schema did not match."""

    def __init__(self, message: str = "Malformed response received from AI provider.", **kwargs: Any) -> None:
        super().__init__(message, code=ProviderErrorCode.MALFORMED_RESPONSE, retryable=False, **kwargs)


class UnsupportedCapabilityError(AIProviderError):
    """Provider does not support requested capability (e.g. tool calling)."""

    def __init__(self, message: str = "Requested capability is unsupported by provider.", **kwargs: Any) -> None:
        super().__init__(message, code=ProviderErrorCode.UNSUPPORTED_CAPABILITY, retryable=False, **kwargs)


class RateLimitExceededError(AIProviderError):
    """Provider rate limit or quota exceeded."""

    def __init__(self, message: str = "AI provider rate limit exceeded.", **kwargs: Any) -> None:
        super().__init__(message, code=ProviderErrorCode.RATE_LIMIT_EXCEEDED, retryable=True, **kwargs)

