"""Authoritative Pydantic schemas for O-Travelz V3 media, video generation, and 3D experiences."""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, ConfigDict
from app.schemas.image import PlaceImageResponse


class VideoPreviewContract(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    video_url: str = Field(..., description="Direct streamable URL to the video preview MP4/WebM")
    poster_url: Optional[str] = Field(None, description="Still poster image frame for initial render")
    provider: str = Field("curated", description="Provider used: veo, kling, runway, curated, mock")
    duration_seconds: float = Field(8.0, description="Length of preview clip in seconds")
    is_ai_generated: bool = Field(False, description="True if generated by AI video model")
    badge_label: str = Field("Video Preview", description="Badge text: 'AI Video Preview' | 'Curated Preview'")
    title: Optional[str] = Field(None, description="Title of the video preview")
    description: Optional[str] = Field(None, description="Short caption of the scene")
    attribution: Optional[str] = Field("Odisha Tourism & O-Travelz Media Engine", description="Source or credit")


class Model3DContract(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    model_id: str = Field(..., description="Unique 3D model identifier")
    name: str = Field(..., description="Name of the 3D subject (e.g. Konark Sun Temple Surya Chakra)")
    format: str = Field("glb", description="Model format: glb, gltf, procedural")
    model_url: Optional[str] = Field(None, description="Direct URL to the downloadable/streamable GLB asset")
    procedural_type: Optional[str] = Field(None, description="Type for built-in Three.js procedural renderer (e.g. konark_wheel, jagannath_temple, dhauli_stupa, barabati_fort, mukteshwar_torana, chilika_boat)")
    thumbnail_url: Optional[str] = Field(None, description="2D thumbnail preview of the 3D subject")
    provider: str = Field("tripo", description="Provider: tripo, meshy, curated, procedural")
    is_ai_generated: bool = Field(True, description="True if generated by Text-to-3D AI model")
    badge_label: str = Field("3D Heritage Model", description="Badge text: 'AI-generated impression' | '3D Heritage Model'")
    transparency_notice: str = Field(
        "AI-generated impression — not a survey-accurate archaeological scan.",
        description="Mandatory transparency notice"
    )
    scale_factor: float = Field(1.0, description="Recommended viewport scale multiplier")
    initial_camera_position: List[float] = Field(default_factory=lambda: [0.0, 2.0, 5.0])
    recommended_lighting: str = Field("golden_hour", description="Recommended preset: daylight, golden_hour, temple_glow, moonlit_night")
    annotations: List[Dict[str, Any]] = Field(default_factory=list, description="Interactive 3D hotspot annotations")


class PlaceMediaResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    place_id: str
    place_name: str
    category: Optional[str] = None
    district: Optional[str] = None
    has_video: bool = False
    has_3d: bool = False
    video: Optional[VideoPreviewContract] = None
    model_3d: Optional[Model3DContract] = None
    images: List[PlaceImageResponse] = Field(default_factory=list)


class VideoGenerationRequest(BaseModel):
    place_id: str
    place_name: str
    prompt_override: Optional[str] = None
    aspect_ratio: str = "16:9"
    duration_seconds: int = 8


class VideoGenerationResponse(BaseModel):
    status: str
    job_id: Optional[str] = None
    video_result: Optional[VideoPreviewContract] = None
    message: Optional[str] = None


class Model3DGenerationRequest(BaseModel):
    place_id: str
    place_name: str
    prompt_override: Optional[str] = None
    quality: str = "standard"


class Model3DGenerationResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    status: str
    job_id: Optional[str] = None
    model_result: Optional[Model3DContract] = None
    message: Optional[str] = None


class ProviderStatusResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    video_provider: str
    video_configured: bool
    video_status: str
    model_3d_provider: str
    model_3d_configured: bool
    model_3d_status: str
    notice: str
