import json
from pathlib import Path

# District Data Map for Odisha's 30 Districts:
# Format: District Name -> {
#   hq_city: str,
#   dhh_name: str,
#   dhh_lat: float, dhh_lon: float, dhh_phone: str, dhh_services: list[str],
#   pharmacy_name: str, pharmacy_lat: float, pharmacy_lon: float, pharmacy_phone: str,
#   atm_bank: str, atm_lat: float, atm_lon: float, atm_loc: str,
#   petrol_name: str, petrol_lat: float, petrol_lon: float, petrol_op: str, petrol_loc: str,
#   police_name: str, police_lat: float, police_lon: float, police_phone: str, police_loc: str,
#   hotel_name: str, hotel_type: str, hotel_lat: float, hotel_lon: float, hotel_price: str, hotel_phone: str, hotel_loc: str,
# }

DISTRICT_MASTER = {
    "Angul": {
        "hq_city": "Angul",
        "dhh_name": "District Headquarters Hospital Angul",
        "dhh_lat": 20.8405, "dhh_lon": 85.1012, "dhh_phone": "06764-230456", "dhh_services": ["Emergency Trauma Unit", "General Medicine", "Pediatrics", "24x7 Dialysis", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Angul Campus)",
        "pharmacy_lat": 20.8407, "pharmacy_lon": 85.1015, "pharmacy_phone": "06764-230458",
        "atm_bank": "State Bank of India", "atm_lat": 20.8385, "atm_lon": 85.1042, "atm_loc": "Collectorate Road, Angul Town",
        "petrol_name": "IndianOil Highway Retail & EV Station", "petrol_lat": 20.8432, "petrol_lon": 85.1120, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "NH-55 Bypass, Angul",
        "police_name": "Angul Town Police Station", "police_lat": 20.8390, "police_lon": 85.1025, "police_phone": "06764-230333", "police_loc": "Near Collectorate Square, Angul",
        "hotel_name": "OTDC Panthanivas Angul", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.8420, "hotel_lon": 85.1050, "hotel_price": "moderate", "hotel_phone": "06764-230678", "hotel_loc": "Raja Chhak, Angul Town",
    },
    "Balangir": {
        "hq_city": "Balangir",
        "dhh_name": "Bhima Bhoi Medical College & Hospital (BBMCH)",
        "dhh_lat": 20.7180, "dhh_lon": 83.4860, "dhh_phone": "06652-232145", "dhh_services": ["24x7 Trauma Center", "ICU", "Cardiology", "Burn Care Unit", "Blood Bank"],
        "pharmacy_name": "Red Cross 24x7 Medicine Store (BBMCH Campus)",
        "pharmacy_lat": 20.7182, "pharmacy_lon": 83.4863, "pharmacy_phone": "06652-232150",
        "atm_bank": "State Bank of India", "atm_lat": 20.7125, "atm_lon": 83.4890, "atm_loc": "Main Branch, Rugudipada, Balangir",
        "petrol_name": "Bharat Petroleum Auto & EV Hub", "petrol_lat": 20.7210, "petrol_lon": 83.4920, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "Patnagarh Road, Balangir",
        "police_name": "Balangir Town Police Station", "police_lat": 20.7140, "police_lon": 83.4875, "police_phone": "06652-232222", "police_loc": "Daily Market Road, Balangir",
        "hotel_name": "OTDC Panthanivas Balangir", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.7155, "hotel_lon": 83.4840, "hotel_price": "budget", "hotel_phone": "06652-232678", "hotel_loc": "Near Rajendra Park, Balangir",
    },
    "Balasore": {
        "hq_city": "Balasore",
        "dhh_name": "Fakir Mohan Medical College & Hospital (FMMCH)",
        "dhh_lat": 21.4925, "dhh_lon": 86.9320, "dhh_phone": "06782-262100", "dhh_services": ["24x7 Emergency", "ICU", "Trauma & Ortho", "Nephrology", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Generic Pharmacy (FMMCH Campus)",
        "pharmacy_lat": 21.4928, "pharmacy_lon": 86.9324, "pharmacy_phone": "06782-262105",
        "atm_bank": "HDFC Bank", "atm_lat": 21.4960, "atm_lon": 86.9280, "atm_loc": "Station Road, Balasore Town",
        "petrol_name": "HP Auto Centre & EV Charging", "petrol_lat": 21.4880, "petrol_lon": 86.9350, "petrol_op": "Hindustan Petroleum Corp Ltd", "petrol_loc": "OT Road, Balasore",
        "police_name": "Balasore Town Police Station", "police_lat": 21.4940, "police_lon": 86.9310, "police_phone": "06782-262002", "police_loc": "Police Line Square, Balasore",
        "hotel_name": "OTDC Panthanivas Chandipur", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 21.4682, "hotel_lon": 87.0145, "hotel_price": "moderate", "hotel_phone": "06782-270051", "hotel_loc": "Sea Beach Road, Chandipur, Balasore",
    },
    "Bargarh": {
        "hq_city": "Bargarh",
        "dhh_name": "District Headquarters Hospital Bargarh",
        "dhh_lat": 21.3340, "dhh_lon": 83.6190, "dhh_phone": "06646-232456", "dhh_services": ["24x7 Casualty & Emergency", "Maternity Wing", "Pathology", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Bargarh)",
        "pharmacy_lat": 21.3342, "pharmacy_lon": 83.6193, "pharmacy_phone": "06646-232460",
        "atm_bank": "State Bank of India", "atm_lat": 21.3310, "atm_lon": 83.6210, "atm_loc": "Bhatli Road, Bargarh",
        "petrol_name": "IndianOil Kissan Seva Kendra", "petrol_lat": 21.3380, "petrol_lon": 83.6150, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "NH-53 Bypass, Bargarh",
        "police_name": "Bargarh Town Police Station", "police_lat": 21.3325, "police_lon": 83.6185, "police_phone": "06646-232222", "police_loc": "Main Road, Bargarh Town",
        "hotel_name": "OTDC Panthanivas Bargarh", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 21.3360, "hotel_lon": 83.6230, "hotel_price": "budget", "hotel_phone": "06646-233100", "hotel_loc": "Near Canal Colony, Bargarh",
    },
    "Bhadrak": {
        "hq_city": "Bhadrak",
        "dhh_name": "District Headquarters Hospital Bhadrak",
        "dhh_lat": 21.0580, "dhh_lon": 86.5120, "dhh_phone": "06784-251234", "dhh_services": ["24x7 Emergency", "Pediatric ICU", "General Surgery", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Bhadrak Campus)",
        "pharmacy_lat": 21.0583, "pharmacy_lon": 86.5123, "pharmacy_phone": "06784-251238",
        "atm_bank": "State Bank of India", "atm_lat": 21.0540, "atm_lon": 86.5160, "atm_loc": "Bonth Chhak, Bhadrak",
        "petrol_name": "Bharat Petroleum Highway Oasis", "petrol_lat": 21.0620, "petrol_lon": 86.5080, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "NH-16 Highway Corridor, Bhadrak",
        "police_name": "Bhadrak Town Police Station", "police_lat": 21.0560, "police_lon": 86.5140, "police_phone": "06784-251022", "police_loc": "Purana Bazar, Bhadrak",
        "hotel_name": "OTDC Panthanivas Chandabali", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.7760, "hotel_lon": 86.7420, "hotel_price": "budget", "hotel_phone": "06786-220325", "hotel_loc": "River Bank Road, Chandabali, Bhadrak",
    },
    "Boudh": {
        "hq_city": "Boudh",
        "dhh_name": "District Headquarters Hospital Boudh",
        "dhh_lat": 20.8390, "dhh_lon": 84.3240, "dhh_phone": "06841-222345", "dhh_services": ["24x7 Emergency", "Maternity Care", "Diagnostic Laboratory", "Blood Bank"],
        "pharmacy_name": "Red Cross Pharmacy (DHH Boudh)",
        "pharmacy_lat": 20.8392, "pharmacy_lon": 84.3243, "pharmacy_phone": "06841-222350",
        "atm_bank": "State Bank of India", "atm_lat": 20.8360, "atm_lon": 84.3270, "atm_loc": "Collectorate Road, Boudh Town",
        "petrol_name": "IndianOil Fuel Station", "petrol_lat": 20.8420, "petrol_lon": 84.3200, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "NH-57 Highway Corridor, Boudh",
        "police_name": "Boudh Town Police Station", "police_lat": 20.8375, "police_lon": 84.3255, "police_phone": "06841-222222", "police_loc": "Near Mahanadi Ghat, Boudh",
        "hotel_name": "OTDC Panthanivas Boudh", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.8400, "hotel_lon": 84.3280, "hotel_price": "budget", "hotel_phone": "06841-222678", "hotel_loc": "Bridge Road, Near Mahanadi Bank, Boudh",
    },
    "Cuttack": {
        "hq_city": "Cuttack",
        "dhh_name": "SCB Medical College & Hospital (Apex State Hospital)",
        "dhh_lat": 20.4782, "dhh_lon": 85.8926, "dhh_phone": "0671-2414080", "dhh_services": ["24x7 Level-1 Trauma Center", "Cardiothoracic ICU", "Neurosurgery", "Burn Center", "Super-Specialty Dialysis"],
        "pharmacy_name": "Jan Aushadhi 24x7 Super Pharmacy (SCBMCH Campus)",
        "pharmacy_lat": 20.4785, "pharmacy_lon": 85.8930, "pharmacy_phone": "0671-2414100",
        "atm_bank": "State Bank of India", "atm_lat": 20.4630, "atm_lon": 85.8820, "atm_loc": "Badambadi Bus Stand Complex, Cuttack",
        "petrol_name": "IndianOil Auto Care & EV Station", "petrol_lat": 20.4580, "petrol_lon": 85.8910, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "Link Road, Badambadi, Cuttack",
        "police_name": "Purighat Police Station", "police_lat": 20.4590, "police_lon": 85.8690, "police_phone": "0671-2419010", "police_loc": "Kathajodi Ring Road, Cuttack",
        "hotel_name": "OTDC Panthanivas Cuttack", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.4795, "hotel_lon": 85.8710, "hotel_price": "moderate", "hotel_phone": "0671-2306916", "hotel_loc": "Near Barabati Fort, Buxi Bazaar, Cuttack",
    },
    "Deogarh": {
        "hq_city": "Deogarh",
        "dhh_name": "District Headquarters Hospital Deogarh",
        "dhh_lat": 21.5360, "dhh_lon": 84.7320, "dhh_phone": "06641-226234", "dhh_services": ["24x7 Emergency", "General Surgery", "Maternity", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Deogarh)",
        "pharmacy_lat": 21.5362, "pharmacy_lon": 84.7323, "pharmacy_phone": "06641-226238",
        "atm_bank": "State Bank of India", "atm_lat": 21.5340, "atm_lon": 84.7350, "atm_loc": "Palasahi, Deogarh Town",
        "petrol_name": "HPCL Highway Retail Outlet", "petrol_lat": 21.5400, "petrol_lon": 84.7280, "petrol_op": "Hindustan Petroleum Corp Ltd", "petrol_loc": "NH-49 Highway, Deogarh",
        "police_name": "Deogarh Town Police Station", "police_lat": 21.5350, "police_lon": 84.7335, "police_phone": "06641-226022", "police_loc": "Near Bus Stand, Deogarh",
        "hotel_name": "OTDC Panthanivas Deogarh", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 21.5380, "hotel_lon": 84.7360, "hotel_price": "budget", "hotel_phone": "06641-226345", "hotel_loc": "Near Pradhanpat Falls Road, Deogarh",
    },
    "Dhenkanal": {
        "hq_city": "Dhenkanal",
        "dhh_name": "District Headquarters Hospital Dhenkanal",
        "dhh_lat": 20.6620, "dhh_lon": 85.5960, "dhh_phone": "06762-225345", "dhh_services": ["24x7 Trauma Unit", "ICU", "Pediatrics", "Blood Bank"],
        "pharmacy_name": "Red Cross Medicine Store (DHH Dhenkanal)",
        "pharmacy_lat": 20.6622, "pharmacy_lon": 85.5963, "pharmacy_phone": "06762-225350",
        "atm_bank": "HDFC Bank", "atm_lat": 20.6650, "atm_lon": 85.5990, "atm_loc": "Baji Rout Chhak, Dhenkanal",
        "petrol_name": "IndianOil Auto & EV Station", "petrol_lat": 20.6580, "petrol_lon": 85.5920, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "Station Road, Dhenkanal",
        "police_name": "Dhenkanal Town Police Station", "police_lat": 20.6635, "police_lon": 85.5975, "police_phone": "06762-225022", "police_loc": "Court Road, Dhenkanal",
        "hotel_name": "OTDC Panthanivas Dhenkanal", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.6680, "hotel_lon": 85.6020, "hotel_price": "budget", "hotel_phone": "06762-224157", "hotel_loc": "Kapilash Road, Dhenkanal",
    },
    "Gajapati": {
        "hq_city": "Paralakhemundi",
        "dhh_name": "District Headquarters Hospital Paralakhemundi",
        "dhh_lat": 18.7780, "dhh_lon": 84.0920, "dhh_phone": "06815-222345", "dhh_services": ["24x7 Emergency", "General Medicine", "Pediatrics", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Paralakhemundi)",
        "pharmacy_lat": 18.7782, "pharmacy_lon": 84.0923, "pharmacy_phone": "06815-222350",
        "atm_bank": "State Bank of India", "atm_lat": 18.7750, "atm_lon": 84.0950, "atm_loc": "Palace Street, Paralakhemundi",
        "petrol_name": "Bharat Petroleum Highway Outlet", "petrol_lat": 18.7820, "petrol_lon": 84.0880, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "Gunupur Road, Paralakhemundi",
        "police_name": "Paralakhemundi Police Station", "police_lat": 18.7765, "police_lon": 84.0935, "police_phone": "06815-222022", "police_loc": "Near Raj Mahal, Paralakhemundi",
        "hotel_name": "OTDC Panthanivas Paralakhemundi", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 18.7790, "hotel_lon": 84.0960, "hotel_price": "budget", "hotel_phone": "06815-222678", "hotel_loc": "Main Road, Paralakhemundi",
    },
    "Ganjam": {
        "hq_city": "Berhampur",
        "dhh_name": "MKCG Medical College & Hospital (Apex Southern Referral)",
        "dhh_lat": 19.3095, "dhh_lon": 84.8105, "dhh_phone": "0680-2292746", "dhh_services": ["24x7 Level-1 Trauma Care", "ICU", "Cardiology", "Nephrology", "Regional Blood Transfusion Center"],
        "pharmacy_name": "Jan Aushadhi 24x7 Super Medicine Store (MKCG Campus)",
        "pharmacy_lat": 19.3098, "pharmacy_lon": 84.8108, "pharmacy_phone": "0680-2292750",
        "atm_bank": "State Bank of India", "atm_lat": 19.3140, "atm_lon": 84.8010, "atm_loc": "New Bus Stand Complex, Berhampur",
        "petrol_name": "IndianOil Auto Care & EV Fast Charger", "petrol_lat": 19.3180, "petrol_lon": 84.7950, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "NH-16 Highway Junction, Berhampur",
        "police_name": "Bada Bazaar Police Station", "police_lat": 19.3080, "police_lon": 84.7920, "police_phone": "0680-2220100", "police_loc": "Bada Bazaar, Berhampur",
        "hotel_name": "OTDC Panthanivas Gopalpur-on-Sea", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 19.2625, "hotel_lon": 84.9080, "hotel_price": "moderate", "hotel_phone": "0680-2243931", "hotel_loc": "Main Beach Road, Gopalpur-on-Sea, Ganjam",
    },
    "Jagatsinghpur": {
        "hq_city": "Jagatsinghpur",
        "dhh_name": "District Headquarters Hospital Jagatsinghpur",
        "dhh_lat": 20.2680, "dhh_lon": 86.1720, "dhh_phone": "06724-220234", "dhh_services": ["24x7 Emergency", "Pediatric Wing", "Orthopedics", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Jagatsinghpur)",
        "pharmacy_lat": 20.2683, "pharmacy_lon": 86.1723, "pharmacy_phone": "06724-220238",
        "atm_bank": "State Bank of India", "atm_lat": 20.2650, "atm_lon": 86.1750, "atm_loc": "Collectorate Chhak, Jagatsinghpur",
        "petrol_name": "Bharat Petroleum Highway Outlet", "petrol_lat": 20.2720, "petrol_lon": 86.1680, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "Cuttack-Machhagaon Road, Jagatsinghpur",
        "police_name": "Jagatsinghpur Town Police Station", "police_lat": 20.2665, "police_lon": 86.1735, "police_phone": "06724-220022", "police_loc": "Thana Chhak, Jagatsinghpur",
        "hotel_name": "OTDC Panthanivas Paradip", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.2650, "hotel_lon": 86.6850, "hotel_price": "moderate", "hotel_phone": "06722-222345", "hotel_loc": "Port Road, Paradip, Jagatsinghpur",
    },
    "Jajpur": {
        "hq_city": "Jajpur",
        "dhh_name": "Jajpur Medical College & Hospital (JMCH)",
        "dhh_lat": 20.8520, "dhh_lon": 86.3350, "dhh_phone": "06728-222345", "dhh_services": ["24x7 Emergency & Trauma", "ICU", "Dialysis Unit", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (JMCH Campus)",
        "pharmacy_lat": 20.8523, "pharmacy_lon": 86.3354, "pharmacy_phone": "06728-222350",
        "atm_bank": "State Bank of India", "atm_lat": 20.8490, "atm_lon": 86.3380, "atm_loc": "Main Market, Jajpur Town",
        "petrol_name": "IndianOil Fuel Station & EV Point", "petrol_lat": 20.8560, "petrol_lon": 86.3310, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "Biraja Temple Road, Jajpur",
        "police_name": "Jajpur Town Police Station", "police_lat": 20.8505, "police_lon": 86.3365, "police_phone": "06728-222022", "police_loc": "Court Square, Jajpur Town",
        "hotel_name": "OTDC Panthanivas Jajpur", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.8540, "hotel_lon": 86.3400, "hotel_price": "budget", "hotel_phone": "06728-222789", "hotel_loc": "Near Biraja Temple, Jajpur Town",
    },
    "Jharsuguda": {
        "hq_city": "Jharsuguda",
        "dhh_name": "District Headquarters Hospital Jharsuguda",
        "dhh_lat": 21.8620, "dhh_lon": 84.0150, "dhh_phone": "06645-272345", "dhh_services": ["24x7 Trauma Care", "ICU", "Industrial Burn Unit", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Jharsuguda)",
        "pharmacy_lat": 21.8623, "pharmacy_lon": 84.0153, "pharmacy_phone": "06645-272350",
        "atm_bank": "HDFC Bank", "atm_lat": 21.8590, "atm_lon": 84.0180, "atm_loc": "Main Road, Near Bus Stand, Jharsuguda",
        "petrol_name": "IndianOil Auto Care & EV Charger", "petrol_lat": 21.8660, "petrol_lon": 84.0110, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "Airport Bypass Road, Jharsuguda",
        "police_name": "Jharsuguda Town Police Station", "police_lat": 21.8605, "police_lon": 84.0165, "police_phone": "06645-272022", "police_loc": "Thana Chhak, Jharsuguda",
        "hotel_name": "OTDC Panthanivas Jharsuguda", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 21.8640, "hotel_lon": 84.0200, "hotel_price": "budget", "hotel_phone": "06645-273100", "hotel_loc": "Near Airport Road, Jharsuguda",
    },
    "Kalahandi": {
        "hq_city": "Bhawanipatna",
        "dhh_name": "Saheed Rendo Majhi Medical College & Hospital (SRMMCH)",
        "dhh_lat": 19.9050, "dhh_lon": 83.1680, "dhh_phone": "06670-230345", "dhh_services": ["24x7 Emergency & Trauma", "ICU", "Cardiology", "Dialysis", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (SRMMCH Campus)",
        "pharmacy_lat": 19.9053, "pharmacy_lon": 83.1684, "pharmacy_phone": "06670-230350",
        "atm_bank": "State Bank of India", "atm_lat": 19.9020, "atm_lon": 83.1710, "atm_loc": "Collectorate Square, Bhawanipatna",
        "petrol_name": "Bharat Petroleum Highway Outlet", "petrol_lat": 19.9090, "petrol_lon": 83.1640, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "NH-26 Highway Corridor, Bhawanipatna",
        "police_name": "Bhawanipatna Town Police Station", "police_lat": 19.9035, "police_lon": 83.1695, "police_phone": "06670-230022", "police_loc": "Daily Market Road, Bhawanipatna",
        "hotel_name": "OTDC Panthanivas Bhawanipatna", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 19.9070, "hotel_lon": 83.1730, "hotel_price": "budget", "hotel_phone": "06670-231122", "hotel_loc": "Near Parmanandpur Chhak, Bhawanipatna",
    },
    "Kandhamal": {
        "hq_city": "Phulbani",
        "dhh_name": "District Headquarters Hospital Phulbani",
        "dhh_lat": 20.4780, "dhh_lon": 84.2340, "dhh_phone": "06842-253345", "dhh_services": ["24x7 Emergency", "Pediatric Wing", "General Surgery", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Phulbani)",
        "pharmacy_lat": 20.4783, "pharmacy_lon": 84.2343, "pharmacy_phone": "06842-253350",
        "atm_bank": "State Bank of India", "atm_lat": 20.4750, "atm_lon": 84.2370, "atm_loc": "Bada Sahi, Phulbani",
        "petrol_name": "IndianOil Kissan Fuel Outlet", "petrol_lat": 20.4820, "petrol_lon": 84.2300, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "Bhubaneswar Road, Phulbani",
        "police_name": "Phulbani Town Police Station", "police_lat": 20.4765, "police_lon": 84.2355, "police_phone": "06842-253022", "police_loc": "Court Road, Phulbani",
        "hotel_name": "OTDC Panthanivas Phulbani", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.4800, "hotel_lon": 84.2390, "hotel_price": "budget", "hotel_phone": "06842-253245", "hotel_loc": "Main Road, Phulbani",
    },
    "Kendrapara": {
        "hq_city": "Kendrapara",
        "dhh_name": "District Headquarters Hospital Kendrapara",
        "dhh_lat": 20.5050, "dhh_lon": 86.4250, "dhh_phone": "06727-232345", "dhh_services": ["24x7 Emergency", "Maternity Hospital", "Dialysis Wing", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Kendrapara)",
        "pharmacy_lat": 20.5053, "pharmacy_lon": 86.4253, "pharmacy_phone": "06727-232350",
        "atm_bank": "State Bank of India", "atm_lat": 20.5020, "atm_lon": 86.4280, "atm_loc": "Tinikonia Bagicha, Kendrapara",
        "petrol_name": "Bharat Petroleum Fuel Station", "petrol_lat": 20.5090, "petrol_lon": 86.4210, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "Cuttack-Chandabali Highway, Kendrapara",
        "police_name": "Kendrapara Town Police Station", "police_lat": 20.5035, "police_lon": 86.4265, "police_phone": "06727-232022", "police_loc": "Near Old Bus Stand, Kendrapara",
        "hotel_name": "OTDC Panthanivas Kendrapara", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.5070, "hotel_lon": 86.4300, "hotel_price": "budget", "hotel_phone": "06727-233120", "hotel_loc": "Near Baladevjew Temple Road, Kendrapara",
    },
    "Keonjhar": {
        "hq_city": "Keonjhar",
        "dhh_name": "Dharani Dhar Medical College & Hospital (DDMCH)",
        "dhh_lat": 21.6320, "dhh_lon": 85.5890, "dhh_phone": "06766-255345", "dhh_services": ["24x7 Trauma Care", "ICU", "Burn Care", "Orthopedics", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DDMCH Campus)",
        "pharmacy_lat": 21.6323, "pharmacy_lon": 85.5894, "pharmacy_phone": "06766-255350",
        "atm_bank": "HDFC Bank", "atm_lat": 21.6280, "atm_lon": 85.5920, "atm_loc": "Mining Road, Keonjhar Town",
        "petrol_name": "IndianOil Auto & EV Station", "petrol_lat": 21.6360, "petrol_lon": 85.5850, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "NH-20 Highway Corridor, Keonjhar",
        "police_name": "Keonjhar Town Police Station", "police_lat": 21.6305, "police_lon": 85.5905, "police_phone": "06766-255022", "police_loc": "Collectorate Road, Keonjhar",
        "hotel_name": "OTDC Panthanivas Keonjhar", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 21.6340, "hotel_lon": 85.5940, "hotel_price": "moderate", "hotel_phone": "06766-253603", "hotel_loc": "Judicial Court Road, Keonjhar Town",
    },
    "Khordha": {
        "hq_city": "Bhubaneswar",
        "dhh_name": "AIIMS Bhubaneswar (Apex National Medical Institute)",
        "dhh_lat": 20.2312, "dhh_lon": 85.7891, "dhh_phone": "0674-2476789", "dhh_services": ["Level-1 Trauma Center 24x7", "Cardiac Care Unit", "Neurosurgery ICU", "Organ Transplant", "Hyperbaric Oxygen"],
        "pharmacy_name": "Jan Aushadhi 24x7 Mega Pharmacy (AIIMS Campus)",
        "pharmacy_lat": 20.2315, "pharmacy_lon": 85.7895, "pharmacy_phone": "0674-2476800",
        "atm_bank": "State Bank of India", "atm_lat": 20.2640, "atm_lon": 85.8440, "atm_loc": "Master Canteen Railway Station, Bhubaneswar",
        "petrol_name": "IndianOil COCO Auto Care & 60kW EV Fast Hub", "petrol_lat": 20.2980, "petrol_lon": 85.8210, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "Jaydev Vihar NH-16 Junction, Bhubaneswar",
        "police_name": "Kharavela Nagar Police Station", "police_lat": 20.2680, "police_lon": 85.8430, "police_phone": "0674-2391210", "police_loc": "Janpath, Unit-3, Bhubaneswar",
        "hotel_name": "OTDC Panthanivas Bhubaneswar", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.2460, "hotel_lon": 85.8320, "hotel_price": "moderate", "hotel_phone": "0674-2432395", "hotel_loc": "Lewis Road, BJB Nagar, Bhubaneswar",
    },
    "Koraput": {
        "hq_city": "Koraput",
        "dhh_name": "Saheed Laxman Nayak Medical College & Hospital (SLNMCH)",
        "dhh_lat": 18.8140, "dhh_lon": 82.7120, "dhh_phone": "06852-250345", "dhh_services": ["24x7 Trauma Center", "ICU", "Dialysis Wing", "Tropical Medicine Unit", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (SLNMCH Campus)",
        "pharmacy_lat": 18.8143, "pharmacy_lon": 82.7124, "pharmacy_phone": "06852-250350",
        "atm_bank": "State Bank of India", "atm_lat": 18.8110, "atm_lon": 82.7150, "atm_loc": "Bus Stand Road, Koraput Town",
        "petrol_name": "IndianOil Highway Outlet", "petrol_lat": 18.8180, "petrol_lon": 82.7080, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "NH-26 Jeypore Road, Koraput",
        "police_name": "Koraput Town Police Station", "police_lat": 18.8125, "police_lon": 82.7135, "police_phone": "06852-250022", "police_loc": "Near Collectorate Square, Koraput",
        "hotel_name": "OTDC Panthanivas Koraput", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 18.8150, "hotel_lon": 82.7180, "hotel_price": "budget", "hotel_phone": "06852-251345", "hotel_loc": "Near Tribal Museum, Koraput",
    },
    "Malkangiri": {
        "hq_city": "Malkangiri",
        "dhh_name": "District Headquarters Hospital Malkangiri",
        "dhh_lat": 18.3540, "dhh_lon": 81.8920, "dhh_phone": "06861-230234", "dhh_services": ["24x7 Emergency", "Pediatric Wing", "General Surgery", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Malkangiri)",
        "pharmacy_lat": 18.3542, "pharmacy_lon": 81.8923, "pharmacy_phone": "06861-230238",
        "atm_bank": "State Bank of India", "atm_lat": 18.3510, "atm_lon": 81.8950, "atm_loc": "Main Road, Malkangiri Town",
        "petrol_name": "Bharat Petroleum Highway Outlet", "petrol_lat": 18.3580, "petrol_lon": 81.8880, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "Jeypore Road, Malkangiri",
        "police_name": "Malkangiri Town Police Station", "police_lat": 18.3525, "police_lon": 81.8935, "police_phone": "06861-230022", "police_loc": "Police Line Square, Malkangiri",
        "hotel_name": "OTDC Panthanivas Malkangiri", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 18.3550, "hotel_lon": 81.8970, "hotel_price": "budget", "hotel_phone": "06861-230567", "hotel_loc": "Near Bus Stand, Malkangiri",
    },
    "Mayurbhanj": {
        "hq_city": "Baripada",
        "dhh_name": "Pandit Raghunath Murmu Medical College & Hospital (PRMMCH)",
        "dhh_lat": 21.9320, "dhh_lon": 86.7260, "dhh_phone": "06792-252100", "dhh_services": ["24x7 Trauma Care", "ICU", "Dialysis Unit", "General Surgery", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (PRMMCH Campus)",
        "pharmacy_lat": 21.9323, "pharmacy_lon": 86.7264, "pharmacy_phone": "06792-252105",
        "atm_bank": "State Bank of India", "atm_lat": 21.9280, "atm_lon": 86.7290, "atm_loc": "Baghra Road, Baripada",
        "petrol_name": "IndianOil Auto & EV Point", "petrol_lat": 21.9360, "petrol_lon": 86.7220, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "NH-18 Highway Corridor, Baripada",
        "police_name": "Baripada Town Police Station", "police_lat": 21.9305, "police_lon": 86.7275, "police_phone": "06792-252022", "police_loc": "Kacheri Road, Baripada",
        "hotel_name": "OTDC Panthanivas Baripada", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 21.9340, "hotel_lon": 86.7320, "hotel_price": "budget", "hotel_phone": "06792-252555", "hotel_loc": "Near Bhanjpur Railway Station, Baripada",
    },
    "Nabarangpur": {
        "hq_city": "Nabarangpur",
        "dhh_name": "District Headquarters Hospital Nabarangpur",
        "dhh_lat": 19.2320, "dhh_lon": 82.5520, "dhh_phone": "06858-222345", "dhh_services": ["24x7 Emergency", "Pediatric Wing", "Maternity", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Nabarangpur)",
        "pharmacy_lat": 19.2323, "pharmacy_lon": 82.5523, "pharmacy_phone": "06858-222350",
        "atm_bank": "State Bank of India", "atm_lat": 19.2290, "atm_lon": 82.5550, "atm_loc": "Main Road, Nabarangpur Town",
        "petrol_name": "Bharat Petroleum Highway Outlet", "petrol_lat": 19.2360, "petrol_lon": 82.5480, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "NH-26 Highway Corridor, Nabarangpur",
        "police_name": "Nabarangpur Town Police Station", "police_lat": 19.2305, "police_lon": 82.5535, "police_phone": "06858-222022", "police_loc": "Near Bus Stand, Nabarangpur",
        "hotel_name": "OTDC Panthanivas Nabarangpur", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 19.2340, "hotel_lon": 82.5580, "hotel_price": "budget", "hotel_phone": "06858-222678", "hotel_loc": "Near Collectorate, Nabarangpur",
    },
    "Nayagarh": {
        "hq_city": "Nayagarh",
        "dhh_name": "District Headquarters Hospital Nayagarh",
        "dhh_lat": 20.1280, "dhh_lon": 85.1050, "dhh_phone": "06753-252345", "dhh_services": ["24x7 Emergency", "General Surgery", "Pediatrics", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Nayagarh)",
        "pharmacy_lat": 20.1282, "pharmacy_lon": 85.1053, "pharmacy_phone": "06753-252350",
        "atm_bank": "State Bank of India", "atm_lat": 20.1250, "atm_lon": 85.1080, "atm_loc": "Khandapada Road, Nayagarh Town",
        "petrol_name": "IndianOil Highway Outlet", "petrol_lat": 20.1320, "petrol_lon": 85.1010, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "NH-57 Highway Corridor, Nayagarh",
        "police_name": "Nayagarh Town Police Station", "police_lat": 20.1265, "police_lon": 85.1065, "police_phone": "06753-252022", "police_loc": "Court Square, Nayagarh",
        "hotel_name": "OTDC Panthanivas Nayagarh", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.1300, "hotel_lon": 85.1100, "hotel_price": "budget", "hotel_phone": "06753-252678", "hotel_loc": "Near Bus Stand, Nayagarh",
    },
    "Nuapada": {
        "hq_city": "Nuapada",
        "dhh_name": "District Headquarters Hospital Nuapada",
        "dhh_lat": 20.8320, "dhh_lon": 82.5340, "dhh_phone": "06678-223345", "dhh_services": ["24x7 Emergency", "General Medicine", "Maternity", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Nuapada)",
        "pharmacy_lat": 20.8322, "pharmacy_lon": 82.5343, "pharmacy_phone": "06678-223350",
        "atm_bank": "State Bank of India", "atm_lat": 20.8290, "atm_lon": 82.5370, "atm_loc": "Collectorate Road, Nuapada",
        "petrol_name": "Bharat Petroleum Highway Outlet", "petrol_lat": 20.8360, "petrol_lon": 82.5300, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "NH-353 Raipur Highway, Nuapada",
        "police_name": "Nuapada Town Police Station", "police_lat": 20.8305, "police_lon": 82.5355, "police_phone": "06678-223022", "police_loc": "Main Road, Nuapada",
        "hotel_name": "OTDC Panthanivas Nuapada", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.8340, "hotel_lon": 82.5400, "hotel_price": "budget", "hotel_phone": "06678-223456", "hotel_loc": "Near Railway Station Road, Nuapada",
    },
    "Puri": {
        "hq_city": "Puri",
        "dhh_name": "District Headquarters Hospital Puri",
        "dhh_lat": 19.8080, "dhh_lon": 85.8230, "dhh_phone": "06752-222045", "dhh_services": ["24x7 Emergency & Trauma", "Heatstroke Management Center", "ICU", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi 24x7 Medicine Hub (DHH Puri)",
        "pharmacy_lat": 19.8083, "pharmacy_lon": 85.8234, "pharmacy_phone": "06752-222050",
        "atm_bank": "State Bank of India", "atm_lat": 19.8050, "atm_lon": 85.8260, "atm_loc": "Grand Road, Near Jagannath Temple, Puri",
        "petrol_name": "IndianOil Coastal Auto Care & EV Fast Charger", "petrol_lat": 19.8120, "petrol_lon": 85.8190, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "VIP Road, Puri",
        "police_name": "Sea Beach Police Station (Tourist Police Beat House)", "police_lat": 19.7990, "police_lon": 85.8290, "police_phone": "06752-222077", "police_loc": "Chakratirtha Road, Sea Beach, Puri",
        "hotel_name": "OTDC Panthanivas Puri", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 19.7960, "hotel_lon": 85.8265, "hotel_price": "moderate", "hotel_phone": "06752-222562", "hotel_loc": "Chakratirtha Road, Sea Beach, Puri",
    },
    "Rayagada": {
        "hq_city": "Rayagada",
        "dhh_name": "District Headquarters Hospital Rayagada",
        "dhh_lat": 19.1680, "dhh_lon": 83.4150, "dhh_phone": "06856-222345", "dhh_services": ["24x7 Emergency Care", "Pediatric Care", "Maternity", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Rayagada)",
        "pharmacy_lat": 19.1682, "pharmacy_lon": 83.4153, "pharmacy_phone": "06856-222350",
        "atm_bank": "State Bank of India", "atm_lat": 19.1650, "atm_lon": 83.4180, "atm_loc": "Station Road, Rayagada",
        "petrol_name": "Bharat Petroleum Highway Outlet", "petrol_lat": 19.1720, "petrol_lon": 83.4110, "petrol_op": "Bharat Petroleum Corporation Ltd", "petrol_loc": "NH-326 Highway Corridor, Rayagada",
        "police_name": "Rayagada Town Police Station", "police_lat": 19.1665, "police_lon": 83.4165, "police_phone": "06856-222022", "police_loc": "Near Daily Market, Rayagada",
        "hotel_name": "OTDC Panthanivas Rayagada", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 19.1700, "hotel_lon": 83.4210, "hotel_price": "budget", "hotel_phone": "06856-222890", "hotel_loc": "Near Bus Stand, Rayagada",
    },
    "Sambalpur": {
        "hq_city": "Sambalpur",
        "dhh_name": "VIMSAR Burla (Apex Western Odisha Referral Institute)",
        "dhh_lat": 21.4980, "dhh_lon": 83.8720, "dhh_phone": "0663-2430768", "dhh_services": ["24x7 Level-1 Trauma Care", "ICU", "Cardiology", "Neurosurgery", "Regional Blood Transfusion Center"],
        "pharmacy_name": "Jan Aushadhi 24x7 Super Pharmacy (VIMSAR Burla)",
        "pharmacy_lat": 21.4983, "pharmacy_lon": 83.8724, "pharmacy_phone": "0663-2430775",
        "atm_bank": "State Bank of India", "atm_lat": 21.4670, "atm_lon": 83.9780, "atm_loc": "Ainthapali Bus Stand Complex, Sambalpur",
        "petrol_name": "IndianOil Auto & EV Fast Charger", "petrol_lat": 21.4720, "petrol_lon": 83.9850, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "NH-53 Highway Bypass, Sambalpur",
        "police_name": "Town Police Station Sambalpur", "police_lat": 21.4640, "police_lon": 83.9720, "police_phone": "0663-2400033", "police_loc": "Gole Bazaar, Sambalpur",
        "hotel_name": "OTDC Panthanivas Sambalpur", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 21.4730, "hotel_lon": 83.9740, "hotel_price": "budget", "hotel_phone": "0663-2411282", "hotel_loc": "Brooks Hill, Near Railway Station, Sambalpur",
    },
    "Subarnapur": {
        "hq_city": "Sonepur",
        "dhh_name": "District Headquarters Hospital Sonepur",
        "dhh_lat": 20.8420, "dhh_lon": 83.9210, "dhh_phone": "06654-220234", "dhh_services": ["24x7 Emergency", "General Surgery", "Maternity", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Kendra (DHH Sonepur)",
        "pharmacy_lat": 20.8422, "pharmacy_lon": 83.9213, "pharmacy_phone": "06654-220238",
        "atm_bank": "State Bank of India", "atm_lat": 20.8390, "atm_lon": 83.9240, "atm_loc": "Main Road, Sonepur Town",
        "petrol_name": "IndianOil Fuel Station", "petrol_lat": 20.8460, "petrol_lon": 83.9170, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "Birmaharajpur Road, Sonepur",
        "police_name": "Sonepur Town Police Station", "police_lat": 20.8405, "police_lon": 83.9225, "police_phone": "06654-220022", "police_loc": "Near Subarnameru Temple Road, Sonepur",
        "hotel_name": "OTDC Panthanivas Sonepur", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 20.8440, "hotel_lon": 83.9260, "hotel_price": "budget", "hotel_phone": "06654-220567", "hotel_loc": "Near Tel River Confluence, Sonepur",
    },
    "Sundargarh": {
        "hq_city": "Rourkela",
        "dhh_name": "Ispat General Hospital (IGH Rourkela)",
        "dhh_lat": 22.2530, "dhh_lon": 84.8620, "dhh_phone": "0661-2510345", "dhh_services": ["24x7 Super Specialty Trauma", "ICU", "Burn Care Super Specialty", "Cardiology", "Blood Bank"],
        "pharmacy_name": "Jan Aushadhi Super Medicine Center (IGH Campus)",
        "pharmacy_lat": 22.2533, "pharmacy_lon": 84.8624, "pharmacy_phone": "0661-2510350",
        "atm_bank": "HDFC Bank", "atm_lat": 22.2480, "atm_lon": 84.8550, "atm_loc": "Bisra Road, Near Railway Station, Rourkela",
        "petrol_name": "IndianOil Auto Care & EV Fast Charger", "petrol_lat": 22.2580, "petrol_lon": 84.8680, "petrol_op": "Indian Oil Corporation Ltd", "petrol_loc": "Panposh Road, Rourkela",
        "police_name": "Plant Site Police Station", "police_lat": 22.2490, "police_lon": 84.8560, "police_phone": "0661-2500022", "police_loc": "Main Road, Rourkela",
        "hotel_name": "OTDC Panthanivas Rourkela", "hotel_type": "hotel_otdc_panthanivas", "hotel_lat": 22.2550, "hotel_lon": 84.8650, "hotel_price": "moderate", "hotel_phone": "0661-2500456", "hotel_loc": "Sector 5, Near Steel Plant, Rourkela",
    }
}

print("Loaded DISTRICT_MASTER with 30 districts successfully.")
